[build]
    command = "npm run build"
    functions="dist-functions"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[functions."updateOneDayVolume"]
schedule = "*/30 * * * *"
